<a href="https://colab.research.google.com/github/camiloch28/landing_experiment_synthetic-analysis/blob/main/landing-experiment-analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Realizar analisis estadistico con T-Test o T de Student

In [1]:
# Comenzamos importando librerías e incluimos la función ttest_ind, que es la que nos permite realizar la prueba t de Student.
import pandas as pd
from scipy.stats import ttest_ind

# Cargar el dataset del experimento
df = pd.read_csv("/content/landing_experiment_synthetic.csv")
df.head()

,id_usuario,pagina,region,dispositivo,conversion,gasto,clics
0,99aa92e9-6dc3-4b18-8a31-fb1442e71d67,A,Norte,Desktop,0,0.00,0
1,99182f6f-325f-499a-815e-5ad414fe1600,B,Norte,Mobile,1,102.86,92
2,774a1f0c-eadb-4c1e-ae10-3058c9594162,B,Centro,Mobile,0,0.00,0
3,6bcc6b1b-56ee-4a7c-b478-01147c2d2cf9,B,Sur,Desktop,0,0.00,0
4,b22abbb3-9919-4974-9288-41212563492c,A,Centro,Mobile,1,76.38,68

Nuestro objetivo es comparar el gasto promedio entre usuarios de la página  A y la página  B. Entonces separamos en estos grupos.

In [2]:
# Separar en grupo A y grupo B
grupo_A = df[(df['pagina'] == 'A')]
grupo_B= df[(df['pagina'] == 'B')]
grupo_B.head()

,id_usuario,pagina,region,dispositivo,conversion,gasto,clics
1,99182f6f-325f-499a-815e-5ad414fe1600,B,Norte,Mobile,1,102.86,92
2,774a1f0c-eadb-4c1e-ae10-3058c9594162,B,Centro,Mobile,0,0.00,0
3,6bcc6b1b-56ee-4a7c-b478-01147c2d2cf9,B,Sur,Desktop,0,0.00,0
7,0e4d3c5f-5520-4328-897d-ef007bcdddea,B,Norte,Desktop,0,0.00,0
8,5992c5a1-554c-4e03-9b25-b2dd107266ed,B,Norte,Mobile,1,66.89,60

Observa que algunos usuarios no se convirtieron en clientes y tienen gasto cero. Dado que no nos interesan, agregamos una segunda condición para filtrar a los que sí compraron. Este paso es clave: no tendría sentido comparar el gasto de usuarios que no compraron.

In [3]:
# Separar en grupo A y grupo B
grupo_A = df[(df['pagina'] == 'A') & (df['conversion'] == 1)]
grupo_B= df[(df['pagina'] == 'B') & (df['conversion'] == 1)]
grupo_B.head()

,id_usuario,pagina,region,dispositivo,conversion,gasto,clics
1,99182f6f-325f-499a-815e-5ad414fe1600,B,Norte,Mobile,1,102.86,92
8,5992c5a1-554c-4e03-9b25-b2dd107266ed,B,Norte,Mobile,1,66.89,60
25,a6837336-3457-44e6-887a-4bd3ffe9b1b7,B,Centro,Desktop,1,56.18,56
27,c586a60b-e26b-4606-b50d-d70da5d52aad,B,Sur,Desktop,1,94.32,94
30,a526bc4d-bf5b-4b95-bbd4-d7972b110c5d,B,Centro,Desktop,1,63.38,63

Comprobamos que tenemos la información que nos interesa y seleccionamos únicamente la columna del gasto, que es la que queremos evaluar.

In [4]:
# Separar en grupo A y grupo B
grupo_A = df[(df['pagina'] == 'A') & (df['conversion'] == 1)]['gasto']
grupo_B= df[(df['pagina'] == 'B') & (df['conversion'] == 1)]['gasto']
grupo_B.head()

1     102.86
8      66.89
25     56.18
27     94.32
30     63.38
Name: gasto, dtype: float64

Con nuestros grupos listos, ejecutamos la función ttest_ind y le pasamos ambos grupos como entrada.

In [5]:
ttest_ind(grupo_A, grupo_B)

TtestResult(statistic=np.float64(-20.74768675846578), pvalue=np.float64(1.4282455772283151e-90), df=np.float64(3722.0))

Observa que el resultado tiene dos elementos, uno llamado statistic y el pvalue.

Para hacerlo más legible, los guardamos y los mostramos junto con un texto más explicativo.

In [6]:
# Ejecutar prueba t y guardar resultados
t_stat, p_value = ttest_ind(grupo_A, grupo_B)

# Visualizar resultados
print(f"Estadístico t: {t_stat}")
print(f"Valor P: {p_value}")

Estadístico t: -20.74768675846578
Valor P: 1.4282455772283151e-90